project_1/english/urls.py
from django.urls import path
from .views import WorldView

urlpatterns = [
    path('', WorldView.as_view(), name='world'),
]

project_1/training_apparatus/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('english.urls')),
]

project_1/english/models.py
from django.db import models


class World(models.Model):

    id = models.AutoField(primary_key=True)
    value_russ = models.CharField(max_length=255, blank=True, null=True, verbose_name='Русский')
    value_eng = models.CharField(max_length=255, blank=True, null=True, verbose_name='English')
    transcription = models.CharField(max_length=255, blank=True, null=True, verbose_name='Транскрипция')
    reads_like = models.CharField(max_length=255, blank=True, null=True, verbose_name='Читается как')
    audio = models.FileField(upload_to='audio/', blank=True, null=True, verbose_name='Звук')
    picture = models.ImageField(upload_to='images/', blank=True, null=True, verbose_name='Картинка')
    part_of_speech = models.CharField(max_length=255, blank=True, null=True, verbose_name='Часть речи')
    top = models.CharField(max_length=255, blank=True, null=True, verbose_name='Вхождение в ТОП')

    class Meta:
        verbose_name = "World"
        verbose_name_plural = "Worlds"

    def __str__(self):
        return self.value_russ

    # def get_absolute_url(self):
    #     return reverse("_detail", kwargs={"pk": self.pk})

project_1/english/views.py
from django.shortcuts import render
from django.views.generic import ListView
from .models import World

class WorldView(ListView):
    model = World
    template_name = 'index.html'

# Create your views here.

project_1/english/templates/index.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Картинка</title>
</head>
    <body>
        <h4>Picture</h4>
        {% for world in world_list %}
            <h5>{{ world.value_russ }} - {{ world.value_eng }}</h5>
            <img src="{{ world.picture.url }}" alt="">
        {% endfor %}
    </body> 
</html>